[build]
command = "yarn build && yarn export"
publish = "out"

[build.environment]
NODE_OPTIONS = "--max_old_space_size=4096"
NODE_VERSION = "15.0.1"
YARN_FLAGS = "--no-ignore-optional"
YARN_VERSION = "1.22.10"
