backend:
  name: github
  repo: hppRC/hppPortfolio
  branch: master

media_folder: static/assets
public_folder: assets

collections:
- name: "mainPages"
  label: "Main Pages and Settings"
  files:
  - file: "src/pages/index.md"
    label: "Home"
    name: "home"
    fields:
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "home-page",
    }
    - { label: Title, name: title, widget: "string" }
    - {
      label: Sections,
      name: sections,
      widget: list,
      fields:
        [
        { label: Title, name: title, widget: string },
        { label: Body, name: body, widget: markdown },
        ]
    }
  - file: "src/pages/config.md"
    label: "Global Settings"
    name: "config"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "hidden-page",
      }
      - { label: Site Title, name: title, widget: "string" }
      - { label: Site Description, name: desc, widget: "string" }
      - {
        label: Menu,
        name: menu_nav,
        widget: list,
        fields:
          [
          { label: Text, name: text, widget: string },
          { label: URL, name: url, widget: string },
          ]
      }
- name: "blog"
  label: "Blog"
  folder: "src/pages/blog"
  create: true
  fields:
  - { name: "title", label: "Title", widget: "string" }
  - { name: path, label: Path }
  - { name: date, label: Date, widget: datetime }
  - { name: "description", label: "Description", widget: "text" }
  - { name: "body", label: "Body", widget: "markdown" }
